/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rfs.h"

int *
rfs_open_1_svc(open_record *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

file_data *
rfs_read_1_svc(read_record *argp, struct svc_req *rqstp)
{
	static file_data  result;

	/*
	 * insert server code here
	 */

	return &result;
}

file_data *
rfs_write_1_svc(write_record *argp, struct svc_req *rqstp)
{
	static file_data  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rfs_close_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
