/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>

int *
rfs_open_1_svc(open_record *argp, struct svc_req *rqstp)
{
	static int result;
	printf("llamada open\n");
	result = open(argp->file_name, argp->flags, S_IRWXU);
	return &result;
}

file_data *
rfs_read_1_svc(read_record *argp, struct svc_req *rqstp)
{
	static file_data result;
	printf("llamada read\n");
	result.file_data_val = (char *) malloc(argp->count);
	if (result.file_data_val == 0)
		result.file_data_len = 0;
	else
		result.file_data_len = read(argp->fd, result.file_data_val, argp->count);
	return &result;
}

file_data *
rfs_write_1_svc(write_record *argp, struct svc_req *rqstp)
{
	static file_data result;

	static ssize_t exito;

	printf("Recibida una llamada write\n");
	result.file_data_val = argp->buffer;

	
	exito = write(argp->fd, argp->buffer, argp->count);

	if (exito == -1)
		result.file_data_len = 0;
	else
		result.file_data_len = 1;
	

	return &result;
}

int *
rfs_close_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	printf("llamada close\n");
	result = close(*argp);
	return &result;
}
