#!/usr/bin/python

print("Content-type: text/html\n")
print()
print("<HTML><BODY>\n")
print("<font color = blue>\n")
print("<TITLE>CGI script output</TITLE>")
print("<h1 style=\"TEXT-ALIGN: center\">HOLA MUNDO</h1>\n")
print("</font>\n")
print("</HTML>")
 
